import { ISupplier } from "./models/supplier";

export const mockDataSupplier: ISupplier[] = [
  {
    id: "1",
    supplierName: "M+C Mail GmbH",
    supplierNameShort: "M+C",
    supplierAdress: {
      streetName: "Menzikerstrasse",
      streetNumber: "25a",
      country: "CH",
      zipCode: 6221,
      city: "Rickenbach LU",
    },
    supplierProducts: {
      outerenvelope: true,
      letter: true,
      flyer: true,
      cards: false,
    },
  },
  {
    id: "2",
    supplierName: "Kuvertdruck Zurwerra AG",
    supplierNameShort: "Zurwerra",
    supplierAdress: {
      streetName: "Weingartenstrasse",
      streetNumber: "68",
      country: "CH",
      zipCode: 3904,
      city: "Naters VS",
    },
    supplierProducts: {
      outerenvelope: true,
      letter: false,
      flyer: false,
      cards: false,
    },
  },
  {
    id: "3",
    supplierName: "Lerchmüller AG",
    supplierNameShort: "Lerchmüller",
    supplierAdress: {
      streetName: "Brunnengässli",
      streetNumber: "1",
      country: "CH",
      zipCode: 5107,
      city: "Schinznach-Dorf AG",
    },
    supplierProducts: {
      outerenvelope: false,
      letter: true,
      flyer: false,
      cards: false,
    },
  },
  {
    id: "4",
    supplierName: "KünzlerBachmann AG",
    supplierNameShort: "Künzlerbachmann",
    supplierAdress: {
      streetName: "Zürcherstrasse",
      streetNumber: "601",
      country: "CH",
      zipCode: 9015,
      city: "St. Gallen SG",
    },
    supplierProducts: {
      outerenvelope: false,
      letter: true,
      flyer: false,
      cards: false,
    },
  },
  {
    id: "5",
    supplierName: "Heller Druck AG",
    supplierNameShort: "Heller",
    supplierAdress: {
      streetName: "Sinserstrasse",
      streetNumber: "2",
      country: "CH",
      zipCode: 6330,
      city: "Cham ZG",
    },
    supplierProducts: {
      outerenvelope: false,
      letter: false,
      flyer: true,
      cards: true,
    },
  },
  {
    id: "6",
    supplierName: "Wolf Druck AG",
    supplierNameShort: "Wolf",
    supplierAdress: {
      streetName: "Schliessa",
      streetNumber: "12",
      country: "LI",
      zipCode: 9495,
      city: "Triesen",
    },
    supplierProducts: {
      outerenvelope: false,
      letter: false,
      flyer: true,
      cards: true,
    },
  },
  {
    id: "7",
    supplierName: "Merkur Druck AG",
    supplierNameShort: "Merkur",
    supplierAdress: {
      streetName: "Gaswerkstrasse",
      streetNumber: "56",
      country: "CH",
      zipCode: 4900,
      city: "Langenthal BE",
    },
    supplierProducts: {
      outerenvelope: false,
      letter: false,
      flyer: true,
      cards: true,
    },
  },
  {
    id: "8",
    supplierName: "Kromer Print AG",
    supplierNameShort: "Kromer",
    supplierAdress: {
      streetName: "Karl Roth-Strasse",
      streetNumber: "3",
      country: "CH",
      zipCode: 5600,
      city: "Lenzburg AG",
    },
    supplierProducts: {
      outerenvelope: false,
      letter: false,
      flyer: true,
      cards: true,
    },
  },
  {
    id: "9",
    supplierName: "Multicolor Print AG",
    supplierNameShort: "Multicolor",
    supplierAdress: {
      streetName: "Sihlbruggstrasse",
      streetNumber: "105a",
      country: "CH",
      zipCode: 6341,
      city: "Baar ZG",
    },
    supplierProducts: {
      outerenvelope: false,
      letter: false,
      flyer: true,
      cards: true,
    },
  },
];
