import { IOuterenvelope } from "./models/outerenvelope";

export const mockDataOuterenvelope: IOuterenvelope[] = [
  {
    id: "1",
    format: "C5",
    windowposition: "Fenster rechts",
    windowsize: "100 x 45 mm",
    closure: "Klappe gummiert",
    paperweight: "100 g/m2",
    paper: "weiss Offset",
    paperlabel: "FSC",
    preprint: "Druckdaten werden von uns geliefert",
    postprint: "abpalettieren",
    price: 3025,
  },
  {
    id: "2",
    format: "C5",
    windowposition: "Fenster links",
    windowsize: "100 x 45 mm",
    closure: "Klappe gummiert",
    paperweight: "100 g/m2",
    paper: "weiss Offset",
    paperlabel: "FSC",
    preprint: "Druckdaten werden von uns geliefert",
    postprint: "abpalettieren",
    price: 3025,
  },
  {
    id: "3",
    format: "C5",
    windowposition: "Fenster rechts",
    windowsize: "100 x 45 mm",
    closure: "Klappe gummiert",
    paperweight: "100 g/m2",
    paper: "braun Kraft",
    paperlabel: "",
    preprint: "Druckdaten werden von uns geliefert",
    postprint: "abpalettieren",
    price: 4660,
  },
  {
    id: "4",
    format: "C5",
    windowposition: "Fenster rechts",
    windowsize: "90 x 35 mm",
    closure: "Klappe gummiert",
    paperweight: "100 g/m2",
    paper: "weiss Offset",
    paperlabel: "FSC",
    preprint: "Druckdaten werden von uns geliefert",
    postprint: "abpalettieren",
    price: 2895,
  },
  {
    id: "5",
    format: "C5/6",
    windowposition: "Fenster rechts",
    windowsize: "100 x 45 mm",
    closure: "Klappe gummiert",
    paperweight: "100 g/m2",
    paper: "weiss Offset",
    paperlabel: "FSC",
    preprint: "Druckdaten werden von uns geliefert",
    postprint: "abpalettieren",
    price: 3375,
  },
  {
    id: "6",
    format: "C5/6",
    windowposition: "Fenster links",
    windowsize: "100 x 45 mm",
    closure: "Klappe gummiert",
    paperweight: "100 g/m2",
    paper: "weiss Offset",
    paperlabel: "FSC",
    preprint: "Druckdaten werden von uns geliefert",
    postprint: "abpalettieren",
    price: 3375,
  },
  {
    id: "7",
    format: "B5",
    windowposition: "Fenster rechts",
    windowsize: "100 x 50 mm",
    closure: "Klappe gummiert",
    paperweight: "100 g/m2",
    paper: "weiss Offset",
    paperlabel: "FSC",
    preprint: "Druckdaten werden von uns geliefert",
    postprint: "abpalettieren",
    price: 4700,
  },
];
